[package]
name = "rust_euler"
version = "0.1.0"
edition = "2021"
authors = ["Jaewhan <ghksdl1595@icloud.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
